version: "2"
services:
  web:
    build: .
    container_name: test_web
    volumes:
    - ./:/var/web
    ports:
    - "80:80"
    depends_on:
    - mysqldb

  mysqldb:
    image: mysql:5.7
    container_name: test_web_mysql
    env_file:
    - ".env"
    environment:
    - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    - MYSQL_DATABASE=${DB_DATABASE}
    ports:
    - "3306:3306"
